### ISSUE TITLE
Nextcloud 13 Support

### ISSUE THREAD

**Issue by ariselseng** [rullzer/files_excludedirs#5]
This app is very useful. Is there a particular reason why this do not support NC 13?

**Comment by kzhui125** [comment]
@cowai 
1. download to apps
2. modify appinfo/info.xml, change 12 to 13
3. composer install
4. enable the extensiion
5. occ config:app:set --value '[".snapshot","anotherfolder", "pattern/*/match"]' files_excludedirs exclude

I can use the extension in nextcloud 13.

**Comment by kzhui125** [comment]
@rullzer  I have submit a pull request

https://github.com/nextcloud/files_excludedirs/pull/6

**Comment by ariselseng** [comment]
@kzhui125 I think I simply kept the folder from 12, and changed the info.xml to 13 and reenabled it.

**Comment by rullzer** [comment]
@kzhui125 thnx. I'll have a look next week!

**Comment by rullzer** [comment]
Fixed with #6
